### ISSUE TITLE
Nothing happen when run program

### ISSUE THREAD

**Issue by namthse03439** [LeThiHyVong/InteractiveGraphCut#4]
Khi anh chạy chương trình sau khi đã add property sheet và thư viện đầy đủ, console hiện ra trong 2s và biến mất, chương trình kết thúc.

**Comment by LeThiHyVong** [comment]
Chương trình chạy bằng danh sách đối số:
InteractiveGraphCut.exe <mode> <đường dẫn>
trong đó:
mode: chế độ chạy của chương trình, bao gồm 3 mode:
- 0: chỉ là load ảnh, đánh dấu seed rồi lưu lại
- 1: load ảnh, đánh dấu seed rồi bắt đầu tách object theo thuật toán
- 2: chức năng chưa hoàn chỉnh, nhưng em định để cho nó là mode bao gồm cả kiểm tra độ chính xác

Trong Visual studio, anh có thể thêm argument cho chương trình khi thực hiện debug bằng cách Project Properties > Debugging > nhập vào Command Arguments theo đúng cú pháp.
Như của em là 1 horse.jpg
